training/benchmarks/driver/log_event.py
*args was not used for function _encode_message, so logging message should be passed as message or keyword args.
=> process message for evaluate, step_begin and init_evaluate log-event

training/kunlunxin/glm-pytorch/README.md, training/kunlunxin/glm-pytorch/config/config_R300x1x1.py, training/kunlunxin/glm-pytorch/config/config_R300x1x2.py, training/kunlunxin/glm-pytorch/config/config_R300x1x4.py, training/kunlunxin/glm-pytorch/config/config_R300x2x8.py, training/kunlunxin/glm-pytorch/config/environment_variables.sh, training/run_benchmarks/config/test_conf.py
Provement:
[kunlunxin_glm_1x1.log](https://github.com/FlagOpen/FlagPerf/files/11206814/rank0.out.log)
[kunlunxin_glm_1x2.log](https://github.com/FlagOpen/FlagPerf/files/11206809/rank0.out.log)
[kunlunxin_glm_1x4.log](https://github.com/FlagOpen/FlagPerf/files/11206807/rank0.out.log)
[kunlunxin_glm_2x8.log](https://github.com/FlagOpen/FlagPerf/files/11206818/rank0.out.log)
=> GLM: add kunlunxin 1x1, 1x2, 1x4, and 2x8 configs

training/run_benchmarks/README_dev.md, training/run_benchmarks/config/cluster_conf.py, training/run_benchmarks/dev.py, training/run_benchmarks/run.py
1. cluster_config文件中增加MASTER_PORT，默认为29501（与start_pytorch_task同步）。在某些case添加过程中遇到卡死现象，可能是PORT不可用导致的超时，但c10d默认timeout为00：30：00，导致现象看起来像卡死。可通过修改MASTER_PORT来尝试修正
2. run.dev添加master-port相关逻辑
3. run.dev在拼接source xx.env前，会检查是否存在这个文件。如不存在，则不拼接；如存在，则拼接，并将source这一句命令的stdout/stderr重定向到log_path/source_env.log.txt。并将source与python3 startxxx拼接方式改为&&。如启动task成功但在log中见不到任何输出，可查看source_env.log.txt，里面有stderr信息
4. 同步上述修改至dev.py
1. 已完成master-port流程测试
2. 已完成无env文件，正确env文件，语法错误env文件测试
3. 上述测试均在faster-rcnn stdcase中进行，以能够开始训练第一个epoch为测试成功标准
=> port and shell

training/run_benchmarks/prepare_in_container.py
而 \<vendor\>/\<model\>-\<framework\> 路径中不包含框架版本信息，如果这里不修改，会导致
找不到对应的路径，使得requirements.txt和extention无法正确安装，而retcode是0，继续往下执行start_\<framework\>_task.sh
截图如下：
最终，case会因缺少依赖而异常停止执行。
=> fix  prepare_in_container

training/benchmarks/faster_rcnn/pytorch/run_pretraining.py
=> fix faster-rcnn for 1x1

training/kunlunxin/bert-pytorch/extern/trainer_adapter.py
因为卡上的算子执行是异步的，在统计1x1的反向时间时需要显示地计算执行同步，否则反向的时间会不准确（比实际偏小）。1x8和2x8的场景下由于需要进行通信，通信过程会执行同步，因而没有上述问题。
=> 修复bert 1x1下的时间统计bug

inference/benchmarks/sam_h/README.md, inference/benchmarks/sam_h/pytorch/__init__.py, inference/benchmarks/sam_h/pytorch/dataloader.py, inference/benchmarks/sam_h/pytorch/evaluator.py, inference/benchmarks/sam_h/pytorch/export.py, inference/benchmarks/sam_h/pytorch/forward.py, inference/benchmarks/sam_h/pytorch/model.py, inference/benchmarks/sam_h/pytorch/model_utils/sam.py, inference/benchmarks/sam_h/pytorch/requirements.txt, inference/configs/sam_h/configurations.yaml, inference/configs/sam_h/parameters.yaml, inference/configs/sam_h/vendor_config/nvidia_configurations.yaml
输入输出采用huggingface的样例图重复config.datasize遍进行
=> SAM stdcase

training/kunlunxin/docker_image/pytorch/pytorch_install.sh, training/kunlunxin/glm-pytorch/config/environment_variables.sh, training/kunlunxin/glm-pytorch/extern/trainer_adapter.py, training/run_benchmarks/config/test_conf.py
由于torch_xmlir版本升级，一些旧的接口在新的torch_xmlir里面被删除，本PR主要修改了kunlunxin GLM的trainer_adapter.py。
=> update kunlunxin glm config

.github/workflows/klx-training-pre-pr-check.yml, .github/workflows/klx-training-remove-image.yml, .github/workflows/klx-training-test-manually.yml, training/kunlunxin/kunlunxin_monitor.py
测试workflow完整示例可参考：https://github.com/dynamicheart/FlagPerf/actions/runs/6977313432/job/18987019681?pr=2
1.  PR的标题（强制）需按照`[kunlunxin][MODEL_NAME][DATASET_PATH] xxx`的格式即可自动触发CI。PR的描述里可以传入三个参数（可选）：`MAX_EPOCH`、`PIP_SOURCE`、`MAX_SAMPLES_TERMINATION`：
2. 需要部署self-hosted  runner，并且打上三个标签：self-hosted、klx、r480，并且设置代理，使其可以与github通信。
部署self-hosted runner的方法：[链接](https://yikun.github.io/2020/04/17/%E8%AE%A9Github-Action%E5%9C%A8%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84%E6%9C%BA%E5%99%A8%E4%B8%8A%E8%B7%91%E8%B5%B7%E6%9D%A5/)
注意点：
-  添加self-hosted runner, 执行config.sh和run.sh 之前需要加上代理 
示例：`http_prpxy=<YOUR_PROXY_ADDR>  && https_prpxy=<YOUR_PROXY_ADDR> && config.sh 以及 
http_prpxy=<YOUR_PROXY_ADDR> && https_prpxy=<YOUR_PROXY_ADDR>` && run.sh
- 在参考github的Add new self-hosted runner 文档，执行`./config.sh --url …
=> [workflow][kunlunxin] add klx training pre-pr-check workflow

training/kunlunxin/mask_rcnn-pytorch/config/config_R300x1x1.py
During the training of Mask-RCNN on a single node with one XPU device, the loss occasionally reached nan  in certain steps.
Down-scaling the learning rate to 0.08 fixed the problem.
=> [kunlunxin] Fix the loss equal to nan problem during mask-rcnn training

training/benchmarks/llava1.5_13b/deepspeed-torch/evaluate/evaluator.py, training/benchmarks/llava1.5_7b/deepspeed-torch/evaluate/evaluator.py
寒武纪团队在适配FlagPerf LLava1.5 7b/13b训练的时候发现一处疑似因datasets库引发的bug，本PR给出了修复代码，bug详细说明如下：
- llava1.5 7b和llava1.5 13b两个模型代码当中均有此bug，以下仅以7b模型代码说明，但PR当中对7b/13b模型代码均做了修复。
- 在llava1.5 7b的requirements.txt中 
https://github.com/FlagOpen/FlagPerf/blob/main/training/benchmarks/llava1.5_13b/deepspeed-torch/requirements.txt 并未指定datasets的版本，因此默认安装会安装最新的datasets版本(截止本PR时间，最新版本为2.20.0)
- 笔者尝试在2.16.0-2.20.0的5个版本下，安装datasets后，执行evaluator.py文件，nvidia评测方案使用MMMU数据集，均会报错如下：
- 于是尝试将datasets库降低至2.15.0，在该版本下，数据集可以正常加载，但是发现加载的数据集当中包含“dev_”开头的数据，如图所示：
而 https://github.com/FlagOpen/FlagPerf/blob/main/training/benchmarks/llava1.5_13b/deepspeed-torch/config/answer_dict_val.json 当中并不包含“dev_”开头的数据,因此在代码https://github.com/FlagOpen/FlagPerf/blob/5a30cd2a92e3185a3e14e2bed9c0939c6e5ed1bf/training/benchmarks/llava1.5_13b/deepspeed-t …
=> [fix] fix llava1.5 7/13b evaluator datasets bug

training/benchmarks/llama3_70B/megatron/run_pretraining.py, training/benchmarks/llama3_8B/megatron/run_pretraining.py, utils/run_cmd.py
寒武纪团队适配flagperf时，遇到下述两个问题：
1、运行时patch操作受版本影响，关联的PR为：https://github.com/FlagOpen/FlagPerf/pull/632
现在此PR重新修改。
2、在多机训练时，subprocess.Popen运行外部命令或脚本时创建子进程，并捕获其输出，但此处未能捕获到子进程的输出，导致多机训练启动后卡住。关联的issue为https://github.com/FlagOpen/FlagPerf/issues/560
排查问题后发现是Popen函数中未显示指定执行（executable）命令的shell为/bin/bash。在寒武纪镜像中，此处使用的shell默认是/bin/sh，符号链接指向的是dash。因此建议这里的Popen显示指定具有更多扩展特性的/bin/bash。
现在此PR中修改。
3、可以通过下述代码查看subprocess执行时使用的默认shell
import subprocess
cmd = 'echo $0'  # $0 通常显示当前 shell 的名称或路径
result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
print("echo is " ,result.stdout.strip())
=> fix patch with cambricon & multi nodes

operation/benchmarks/bitwise_and/main.py, operation/benchmarks/bitwise_not/main.py, operation/benchmarks/bitwise_or/main.py
fix bitwise perf test's input not in device
=> cambricon: fix bitwise perf test's input not in device

base/run.py, training/benchmarks/llava1.5_13b/deepspeed-torch/evaluate/evaluator.py, training/benchmarks/llava1.5_13b/deepspeed-torch/train/train_mem.py, training/benchmarks/llava1.5_7b/deepspeed-torch/evaluate/evaluator.py, training/benchmarks/llava1.5_7b/deepspeed-torch/train/train_mem.py, training/run_benchmarks/run.py, utils/sys_monitor.py
寒武纪团队针对自身软件栈的适配需求对flagperf代码进行修改适配，适配改动如下：
- 当前ipmitool命令在寒武纪平台仅获取到机头服务器功耗，不包括box功耗，适配后的代码获取的功耗包括机头服务器功耗+box功耗，即整机功耗。
- utils/sys_monitor.py 添加传入vendor支持以此来识别cambricon mlu，默认vendor=“nvidia”,不对其他厂家产生影响
- base/run.py 调用sys_monitor.py处 传入-v 以此来识别cambricon mlu
- training/run_benchmarks/run.py 调用sys_monitor.py处 传入-v 以此来识别cambricon mlu
- train_mem.py和evaluator.py引入对寒武纪软件栈的支持，同时不会对其他设备产生影响。（已测试）
=> feat(cambricon):improve sys_monitor.py and llava1.5b for cambricon mlu

base/benchmarks/computation-BF16/main.py, base/benchmarks/computation-FP16/main.py, base/benchmarks/computation-FP32/main.py, base/benchmarks/computation-TF32/main.py, base/benchmarks/interconnect-MPI_interserver/main.py, base/benchmarks/interconnect-MPI_intraserver/main.py, base/benchmarks/interconnect-P2P_interserver/main.py, base/benchmarks/interconnect-P2P_intraserver/main.py, base/benchmarks/interconnect-h2d/main.py, base/benchmarks/main_memory-bandwidth/main.py, base/benchmarks/main_memory-capacity/main.py
寒武纪软件栈为非兼容cuda生态形式，因此对于cuda代码需要在运行代码启动处添加兼容代码，本次PR对每个benchmark项下的main.py插入兼容代码，同时不影响其他GPU,详情见files changed。
=> FlagPerf Benchmark 支持寒武纪芯片

training/benchmarks/chatglm3_6b/deepspeed/chatglm3_6b_hf/modeling_chatglm.py
Using torch.ones to init rmsnorm weight. And torch.empty gets random weight tensor, which maybe out of float value limits.
@KerwinKai @shh2000
=> fix rmsnorm init weight bug.

training/utils/start_task_helper.py
1、原始代码说明
对于多机训练，主节点在ssh到每个节点后启动flagscale进程（包括主节点），启动进程时获取该进程PID。先将在前一个节点保存的PID文件删除，然后重新覆写入当前节点的PID，直至达到最后一个节点。
2、问题说明
（1）在寒武纪镜像中执行四机（多机）训练时，主节点在其他子节点依次启动flagscale进程并获取和覆写PID进程号。但是其他节点在启动flagscale后，启动进程（初始化进程）在启动了实际工作的子进程后便退出了，获取的PID也即失效。
（2）wait_for_finish函数中判断传入的PID是否仍在运行，以决定是否中断程序。由于获取的PID失效，所以程序会在各个节点立即提前中止。
3、修改说明
在各个节点启动程序后，通过 ps -aux | grep "MLU_VISIBLE_DEVICES"获取真正运行的进程号，并保存在文件中。
=> [cambricon] Fix MLU PID retrieval issue in nnodes FlagScale training

operation/benchmarks/addmm/kunlunxin/R300p/case_config.yaml, operation/benchmarks/addmm/kunlunxin/R300p/env.sh, operation/benchmarks/bmm/kunlunxin/R300p/case_config.yaml, operation/benchmarks/bmm/kunlunxin/R300p/env.sh, operation/benchmarks/linear/kunlunxin/R300p/case_config.yaml, operation/benchmarks/linear/kunlunxin/R300p/env.sh, operation/benchmarks/max/kunlunxin/R300p/env.sh, operation/benchmarks/min/kunlunxin/R300p/env.sh, operation/benchmarks/mm/kunlunxin/R300p/case_config.yaml, operation/benchmarks/mm/kunlunxin/R300p/env.sh
* blas op support (with customized shape)
* mm
* addmm
* bmm
* linear
* env var fix
* min
* max
* cross_entropy_loss
=> [KUNLUNXIN] add FlagGems blas op support & minor fix for env vars

training/benchmarks/llava1.5_7b_continuetrain/flagscale/run_pretraining.py
1、原始代码说明
在while循环外创建info_line列表，循环内每次间隔300秒访问生成的log文件，并将含有"elapsed time per iteration"字符串的信息append到info_line列表中，只有当列表长度等于迭代步数 getattr(module, "steps") 时跳出while循环。
2、问题说明
当while循环访问到未完成包含所有信息的log时，已有的部分信息仍然会被append到info_line列表；下一次间隔300秒后，会再次将完整的（假设此时log已完成记录所有迭代步）信息append。则列表长度大于getattr(module, "steps")，则一直处于while循环内空转，导致进程无法结束。
3、修改说明
将info_line列表的初始化放在while循环内，每一次append都是独立操作，直到获得完整迭代数，满足跳出while循环条件。
=> [cambricon] Resolve infinite loop issue when retrieving logs

base/toolkits/interconnect-MPI_interserver/mthreads/S5000/main.sh
=> [mthreads] base/toolkits: fix err about MPI
