- training/benchmarks/glm/README.md
- training/benchmarks/glm/pytorch/config/_base.py
- training/benchmarks/glm/pytorch/config/mutable_params.py
- training/benchmarks/glm/pytorch/model/models/transformer.py
- training/benchmarks/glm/pytorch/readme.md
1. Original GLM repo: https://github.com/THUDM/GLM
2. add required parameters: vendor and name for config/_base.py
3. add vendor to mutable_params.py to receive vendor from argparse.
> GLM pytorch case: upgrade to latest version

- training/benchmarks/glm/pytorch/dataloaders/dataloader.py
- training/benchmarks/glm/pytorch/schedulers/base.py
- training/benchmarks/glm/pytorch/train/evaluator.py
- training/benchmarks/glm/pytorch/train/trainer.py
- training/benchmarks/glm/pytorch/train/trainer_adapter.py
…and remove apex dependency from benchmarks directory
> GLM PyTorch: add non-distributed training support, fix fp32 training and remove apex dependency from benchmarks directory

- training/benchmarks/bert/pytorch/config/_base.py
- training/benchmarks/bert/pytorch/config/mutable_params.py
1. fix vendor for argparser
2. fix issues for data_dir and train_dir check
> fix: vendor for bert-pytorch case

- README.md
- training/run_benchmarks/config/test_conf.py
- training/run_benchmarks/run.py
add GEN(short for generation)mode for test_config
merge the path in host/container
fix get_valid_cases, still return valid cases, dropout invalid
add check at get_config_from_case
update readme
> test_config gen mode

- training/run_benchmarks/prepare_in_container.py
fix install extension's bug for prepare_in_container.py
> fix install extension's bug

- training/benchmarks/transformer/README.md
- training/kunlunxin/transformer-pytorch/README.md
- training/kunlunxin/transformer-pytorch/config/config_R300x1x8.py
- training/kunlunxin/transformer-pytorch/config/config_common.py
- training/kunlunxin/transformer-pytorch/config/requirements.txt
- training/kunlunxin/transformer-pytorch/csrc/make_batches.cpp
- training/kunlunxin/transformer-pytorch/csrc/setup.py
transformer model support kunlunxin xpu
> transformer model, support kunlunxin xpu

- README.md
add huawei/upd caselist/fix typo
> Upd Readme

- training/benchmarks/tacotron2/README.md
- training/iluvatar/tacotron2-pytorch/README.md
- training/iluvatar/tacotron2-pytorch/config/config_BI-V100x1x8.py
- training/iluvatar/tacotron2-pytorch/config/config_common.py
- training/iluvatar/tacotron2-pytorch/config/requirements.txt
[iluvatar_tacotron2_BI_V100x8.zip](https://github.com/FlagOpen/FlagPerf/files/12010097/iluvatar_tacotron2_BI_V100x8.zip)
> add Iluvatar tacotron2 case.

- training/benchmarks/resnet50/pytorch/run_pretraining.py
- training/benchmarks/resnet50/pytorch/train/trainer.py
> fix resnet50 for 1x1

- training/benchmarks/mask_rcnn/pytorch/config/_base.py
- training/iluvatar/mask_rcnn-pytorch/README.md
- training/iluvatar/mask_rcnn-pytorch/config/config_BI-V100x1x8.py
- training/iluvatar/mask_rcnn-pytorch/config/config_common.py
- training/iluvatar/mask_rcnn-pytorch/config/environment_variables.sh
- training/iluvatar/mask_rcnn-pytorch/config/requirements.txt
[mask_rcnn.tar.gz](https://github.com/FlagOpen/FlagPerf/files/12027138/mask_rcnn.tar.gz)
> add Iluvatar mask_rcnn case

- training/iluvatar/transformer-pytorch/README.md
- training/iluvatar/transformer-pytorch/config/config_BI-V100x1x8.py
- training/iluvatar/transformer-pytorch/config/config_common.py
- training/iluvatar/transformer-pytorch/config/requirements.txt
- training/iluvatar/transformer-pytorch/csrc/make_batches.cpp
- training/iluvatar/transformer-pytorch/csrc/setup.py
[transformer_log.tar.gz](https://github.com/FlagOpen/FlagPerf/files/12190332/transformer_log.tar.gz)
> Iluvatar transformer

- training/benchmarks/cpm/pytorch/train/evaluator.py
- training/benchmarks/cpm/pytorch/train/trainer.py
- training/benchmarks/cpm/pytorch/train/trainer_adapter.py
在nv上验证了1x1, 1x8
在昆仑芯R300上验证了1x1, 1x8
> fix cpm 1x1 for FP32

- training/benchmarks/driver/helper.py
快速修复非cuda兼容模式下的kunlunxin的seed问题
> fix "set_seed" problem on kunlunxin

- training/benchmarks/llama2_7b/deepspeed/run_pretraining.py
- training/run_benchmarks/config/test_conf.py
> fix llama, add TFLOPS log

- training/ascend/aquila2_7B_container-in_container/Dockerfile
- training/ascend/aquila2_7B_container-in_container/config.py
- training/ascend/aquila2_7B_container-in_container/requirements.txt
- training/ascend/aquila2_7B_container-in_container/singlenode_adapt.sh
- training/ascend/aquila2_7B_container-in_container/singlenode_correctness.sh
update aquila2 7B config and scripts
> [Ascend] Support Aquila2 7B

- training/ascend/display_line.py
- training/ascend/scatter_npu.py
- training/ascend/standalone_monitor.py
> [Ascend] update monitor

- training/ascend/aquila2_7B_container-in_container/singlenode_adapt.sh
> [Ascend]Update Aquila2-7B script

- training/ascend/display_line.py
- training/ascend/scatter_npu.py
modify training/ascend/display_line.py
modify training/ascend/scatter_npu.py
> [Ascend] modify monitor

- training/run_benchmarks/config/test_conf.py
[metax] add waveglow case on test_conf.py
> [metax] add waveglow case on test_conf.py

- training/iluvatar/docker_image/megatron-deepspeed/Dockerfile
- training/iluvatar/docker_image/megatron-deepspeed/megatron-deepspeed_install.sh
- training/iluvatar/docker_image/megatron-deepspeed/packages/README.md
- training/iluvatar/docker_image/megatron-deepspeed/sdk_installers/README.md
- training/iluvatar/llama3_8B-megatron-deepspeed/README.md
- training/iluvatar/llama3_8B-megatron-deepspeed/config/config_BI-V150x1x16.py
- training/iluvatar/llama3_8B-megatron-deepspeed/config/requirements.txt
- training/iluvatar/llama3_8B-megatron-deepspeed/config/training_adapter.sh
1. add iluvatar megatron-deepspeed docker image
2. add iluvatar llama3 8b training config.
[iluvatar_llama3_8B.zip](https://github.com/user-attachments/files/16027083/iluvatar_llama3_8B.zip)
> [iluvatar] add iluvatar LLama3 8B.

- training/benchmarks/chatglm3_6b/deepspeed/run_pretraining.py
Support gradient_checkpointing option in ChatGLM3_6B standard case which enabling more flexible configuration
> [Kunlunxin] Support gradient_checkpointing for chatglm3_6b std case

- base/benchmarks/drivers/utils.py
> feat(base/benchmark):support cambricon mlu tf32

- training/kunlunxin/baichuan2_13b-deepspeed/README.md
- training/kunlunxin/baichuan2_13b-deepspeed/config/config_R300x2x8.py
- training/kunlunxin/baichuan2_13b-deepspeed/config/ds_config.json
- training/kunlunxin/baichuan2_13b-deepspeed/config/environment_variables.sh
Add baichuan2_13b case, run on 2x8
> [kunlunxin] Add baichuan2_13b 2x8 case

- operation/benchmarks/silu/kunlunxin/R300p/case_config.yaml
- operation/benchmarks/silu/main.py
- operation/vendors/kunlunxin/xpytorch029/xpytorch029_install.sh
* FlagGems: switch to branch v2.0-perf-klx
* silu: add shape config customization
> [KUNLUNXIN] FlagGems install & silu op update

- operation/benchmarks/dropout/cambricon/MLU/case_config.yaml
- operation/benchmarks/pow/cambricon/MLU/case_config.yaml
change configs for dropout/pow
> [cambricon]: change configs

- operation/benchmarks/all/main.py
bugfix for operation `all'：
arange_end customization, not shape
> [KUNLUNXIN] bugfix for op 'all'

- base/benchmarks/interconnect-P2P_intraserver/metax/C550/case_config.yaml
best config for metax P2P intraserver
> Update case_config.yaml  best config for metax P2P intraserver test

- operation/benchmarks/drivers/calculate.py
- operation/configs/host.yaml
- operation/vendors/cambricon/camtorch0830/Dockerfile
- operation/vendors/cambricon/camtorch0830/camtorch0830_install.sh
add dockerfile and opt find path
> [cambricon]: add dockerfile and opt find path

- base/configs/host.yaml
- base/toolkits/computation-BF16/kunlunxin/R300p/main.sh
- base/toolkits/computation-FP16/kunlunxin/R300p/main.sh
- base/toolkits/computation-FP32/kunlunxin/R300p/main.sh
- base/toolkits/computation-INT8/kunlunxin/R300p/main.sh
- base/toolkits/computation-TF32/kunlunxin/R300p/main.sh
- base/toolkits/interconnect-MPI_interserver/kunlunxin/R300p/main.sh
- base/toolkits/interconnect-MPI_intraserver/kunlunxin/R300p/main.sh
- base/toolkits/interconnect-P2P_interserver/kunlunxin/R300p/main.sh
- base/toolkits/interconnect-P2P_intraserver/kunlunxin/R300p/main.sh
- base/toolkits/interconnect-h2d/kunlunxin/R300p/main.sh
- base/toolkits/main_memory-bandwidth/kunlunxin/R300p/main.sh
- base/toolkits/main_memory-capacity/kunlunxin/R300p/main.sh
- base/vendors/kunlunxin/pytorch_2.0/Dockerfile
- base/vendors/kunlunxin/pytorch_2.0/pytorch_2.0_install.sh
*   interconnect-MPI_intraserver
*   interconnect-P2P_intraserver
*   interconnect-MPI_interserver
*   interconnect-P2P_interserver
*   interconnect-h2d
*   main_memory-bandwidth
*   main_memory-capacity
*   computation-FP32
*   computation-FP16
*   computation-BF16
*   computation-INT8
*   computation-TF32
> [KUNLUNXIN] base case add toolkits support

- base/vendors/mthreads/pytorch_2.2/Dockerfile
> [mthreads] Update base/vendors: update dockerfile

- training/iluvatar/llama3_8B-megatron/config/config_TG-V200x1x16.py
set theoryflops to calculate MFU
> [iluvatar] llama3 8B training test setting fix

- base/vendors/iluvatar/pytorch_2.1/Dockerfile
iluvatar base test: update BI150 pytorch dockerfile
> [iluvatar] base/vendor: update BI150 pytorch dockerfile for base test
